baseURL = "https://chrislabarge.com/"
languageCode = "en-us"
title = "Chris LaBarge - Software Developer - Portfolio"
theme = "elephants"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 2
[params]
    activeTaxClass = "active"
    sitename = "Chris LaBarge"
    imgAlt = "A image that is associated to the content below. Sometimes a play on words."
    description = "Chris LaBarge is a software developer living in Albany New York, who specializes in building web applications using Ruby on Rails"
