baseURL = "http://chrislabarge.com/"
languageCode = "en-us"
title = "Chris LaBarge"
theme = "elephants"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 2

[params]
    sitename = "Chris LaBarge"
